version: "3.8"

services:
  app:
    build: .
    environment:
      PG_HOST: db
      PG_PORT: 5432
      PG_USER: youruser
      PG_PASSWORD: yourpassword
      PG_DB_NAME: spy_cat_agency
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: spy_cat_agency
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
